import { Inter } from "next/font/google";
import "./globals.css";
import "keen-slider/keen-slider.min.css";
import Link from "next/link";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="p-2 flex gap-4 bg-orange-500 text-gray-100 justify-center">
          contact us!
        </div>
        <header className="p-6 flex gap-4 bg-slate-100 text-gray-700 sticky top-0 z-50 bg-white shadow">
          <Link href="/">
            <Image src="/logo/Logo-r.png" alt="建築1" className="w-18 h-8" />
          </Link>
          <Link href="/contact" className="hover:underline">
            Services
          </Link>
          <Link href="/contact" className="hover:underline">
            Our Projects
          </Link>
          <Link href="/contact" className="hover:underline">
            Who We Are
          </Link>
          <Link href="/contact" className="hover:underline">
            Contact us
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
